name: CI
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
          - dev
          - qa
          - stg
          - trn
      applications:
        required: true
        
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Log 1st Critical Step
        run: | 
          touch log_steps > ./artifacts
          echo "Step 1" >> log_steps
      - uses: actions/upload-artifact@v3
        with: 
          name: log_steps
          path: ./artifacts

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Log 2nd Critical Step
        run: | 
          echo "Step 2" >> log_steps
      - uses: actions/upload-artifact@v3
        with: 
          name: log_steps
          path: ./artifacts
