name: CD2
on:
  workflow_run:
    workflows: [CI]
    types: 
      - completed
      
jobs:
  execute:
    if:  ${{ github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.conclusion == 'cancelled' }}
    runs-on: ubuntu-latest
    steps: 
      - name: get_job_steps_conclusions
        uses: actions/github-script@v6
        with:
          script: |
            let workflowRunJobs = await github.rest.actions.listJobsForWorkflowRunAttempt({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
              attempt_number: context.payload.workflow_run.run_attempt
            });
            for(let jobStep of workflowRunJobs.data.jobs[0].steps){
              let stepConclusion = jobStep.conclusion;
              console.log(stepConclusion); 
              console.log(jobStep.id); 
              if(stepConclusion === 'cancelled' || stepConclusion === 'failed'){
                core.setOutput('stepsOutput', jobStep.name);
              }
            }
            
            
      - name: find_failed_step
        run: |
           echo ${{ steps.get_job_steps_conclusions.outputs.stepsOutput }}
        
      
