name: CI
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        options:
          - dev
          - qa
          - stg
          - trn
      applications:
        required: true
        
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: create_input_artifacts
        id: "create_input_artifacts"
        run: |
          mkdir -p artifacts
          echo "env:$inputs.environment" > ./artifacts/artifact_inputs
          echo "applications:$inputs.applications" >> ./artifacts/artifact_inputs
      - uses: actions/upload-artifact@v3
        with:
          name: artifact_inputs
          path: ./artifacts/
        
      # Runs a single command using the runners shell
      - name: stop_ecs
        id: "stop_ecs"
        run: |
          echo "Stopping ECS"
          sleep 5s

      # Runs a single command using the runners shell
      - name: manual_intervention
        id: "manual_intervention"
        run: |
          echo "Manual Intervention"
          chmod 700 ./bin/manual_intervention.sh
          ./bin/manual_intervention.sh -g ${GITHUB_TOKEN} -t ${ github.actor }
          
      # Runs a single command using the runners shell
      - name: update_ssm_parameters
        id: "update_ssm_parameters"
        run: |
          echo "Updating SSM Parameters"
          sleep 5s
          
      # Runs a single command using the runners shell
      - name: restore_ecs
        id: "restore_ecs"
        run: |
          echo "Restoring ECS"
          sleep 5s
