name: CD2
on:
  workflow_run:
    workflows: [CI]
    types: 
      - completed
      
jobs:
  execute:
    if:  ${{ github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.conclusion == 'cancelled' }}
    runs-on: ubuntu-latest
    steps: 
      - name: get_job_steps_conclusions
        id: get_job_steps_conclusions
        uses: actions/github-script@v6
        with:
          script: |
            let workflowRunJobs = await github.rest.actions.listJobsForWorkflowRunAttempt({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
              attempt_number: context.payload.workflow_run.run_attempt
            });
            for(let jobStep of workflowRunJobs.data.jobs[0].steps){
              console.log(jobStep);
              let stepConclusion = jobStep.conclusion;
              console.log(stepConclusion); 
              if(stepConclusion === 'cancelled' || stepConclusion === 'failed'){
                core.setOutput('stepsOutput', jobStep.name);
                core.setOutput('stepConclusion', stepConclusion);
                break;
              }
            }
            
            
      - name: action_based_on_faulty_step
        run: |
           chmod 700 ./bin/action_based_on_faulty_step.sh
           ./bin/action_based_on_faulty_step.sh -s steps.get_job_steps_conclusions.outputs.stepsOutput -c steps.get_job_steps_conclusions.outputs.stepConclusion
        
      
